version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ai_blog_web
    command: /start-server
    volumes:
      - .:/app
    ports:
      - 8010:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=dlearn
      - POSTGRES_USER=dlearn
      - POSTGRES_PASSWORD=dlearn
volumes:
  postgres_data:
