# Generated by Django 3.2.8 on 2021-12-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
    ]
