# Generated by Django 4.0 on 2022-05-21 13:50

import course.models
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_usercourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=pathlib.PureWindowsPath('D:/learning/university/IMPORTANT!/dlearn/uploads/default/default_image.png'), max_length=256, upload_to=course.models.course_directory_path),
        ),
    ]
