# Generated by Django 4.0.5 on 2022-06-24 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_auto_20211215_1520'),
        ('course', '0008_alter_usercourse_course_alter_usercourse_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='courses', through='course.UserCourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
