# Generated by Django 4.0.4 on 2022-05-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220329_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
