# Generated by Django 4.0.4 on 2022-05-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
