# Generated by Django 4.0.4 on 2022-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdetail',
            name='mark',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
