# Generated by Django 4.0.4 on 2022-05-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_resultdetail_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdetail',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
