# Generated by Django 4.0.4 on 2022-05-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_resultdetail_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
