# Generated by Django 4.0 on 2021-12-08 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=40, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='FirstName')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='LastName')),
                ('patronymic', models.CharField(max_length=30, null=True, verbose_name='Patronymic')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='CreatedAt')),
                ('role', models.IntegerField(choices=[(0, 'common_user'), (1, 'admin')], default=0)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
