# Generated by Django 4.0 on 2021-12-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biology_sex',
            field=models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female')], default=1, verbose_name='Biology Sex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
    ]
