# Generated by Django 3.2.8 on 2021-12-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_biology_sex_customuser_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='biology_sex',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
    ]
