# Generated by Django 4.0 on 2021-12-14 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_media_alter_task_mark_usertaskfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='do_up_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Do Up To'),
        ),
    ]
