# Generated by Django 3.2.8 on 2021-12-19 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_usercourse_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0005_alter_task_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='mark',
        ),
        migrations.AddField(
            model_name='task',
            name='max_mark',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Mark'),
        ),
        migrations.AlterField(
            model_name='ownertaskfile',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=task.models.owner_directory_path, verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='task',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='usertaskfile',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=task.models.user_directory_path, verbose_name='Media'),
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mark')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Done At')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
