# Generated by Django 3.2.8 on 2022-01-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20211219_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
