# Generated by Django 4.0.4 on 2022-05-04 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_task_has_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='has_quiz',
        ),
        migrations.RemoveField(
            model_name='task',
            name='max_mark',
        ),
    ]
