# Generated by Django 4.0.4 on 2022-05-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_remove_task_has_quiz_remove_task_max_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_quiz',
            field=models.BooleanField(default=False, verbose_name='Has Quiz'),
        ),
    ]
