# Generated by Django 4.0.4 on 2022-05-09 10:59

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_ownertaskfile_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='done_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Done At'),
        ),
        migrations.AlterField(
            model_name='usertaskfile',
            name='media',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=task.models.user_directory_path, verbose_name='Media'),
        ),
    ]
