# Generated by Django 4.0.4 on 2022-05-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_remove_task_has_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_mark',
            field=models.IntegerField(default=0),
        ),
    ]
