# Generated by Django 4.0.4 on 2022-05-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_task_max_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='is_examined',
            field=models.BooleanField(default=False),
        ),
    ]
