# Generated by Django 4.0 on 2022-05-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_usertaskfile_done_at_usertaskfile_too_late'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='mark',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Mark'),
        ),
    ]
