# Generated by Django 5.0.7 on 2024-07-21 22:24

import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('group_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='GroupName')),
                ('join_code', models.CharField(max_length=20, unique=True, verbose_name='JoinCode')),
                ('image', models.ImageField(default=pathlib.PureWindowsPath('C:/Users/kodokawai/Desktop/Python/my-projects/dlearn/uploads/default/default_image.png'), max_length=256, upload_to='')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='CreatedAt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='courses', through='course.UserCourse', to=settings.AUTH_USER_MODEL),
        ),
    ]
