# Generated by Django 5.0.7 on 2024-07-21 22:25

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default=pathlib.PurePosixPath('/app/uploads/default/default_image.png'), max_length=256, upload_to=''),
        ),
    ]
