# Generated by Django 5.0 on 2024-07-22 18:15

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default=pathlib.PureWindowsPath('C:/Users/kodokawai/Desktop/Python/my-projects/dlearn-project/dlearn/media/default/default_image.png'), max_length=256, upload_to=''),
        ),
    ]
