# Generated by Django 5.0 on 2024-07-22 19:34

import dlearn.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='/static/course/images/default_image.png', max_length=256, storage=dlearn.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
